### PR TITLE
chore(ci): add stale bot for issues

### LINKED ISSUE #285: Requesting a working guide for modelling multi component and its deployment via ocm-controller.
**What would you like to be added**:
- Needed the example guide or documentation, The documentation should describe, how to model a component consisting of several child components.
- It should be added in https://ocm.software/docs/guides/getting-started-with-ocm-flux/ .

**Why is this needed**:
-  For the deployment of multiple OCM components with root - reference (parent-child) approach  .
-  We need example for better understanding the relations between parent and child component through "reference.yaml" .
-  Using root - reference approach , there are separate component descriptors has been created for each component , and there is a component descriptors for parent as well, we need to understand how it is getting referenced .
-  And how ocm - controller will pick the child components , if parent componentversion.yaml is getting deployed on cluster ? .

### PR DESCRIPTION
**Pull request by jakobmoellerdev**
#### What this PR does / why we need it

Adds a stale bot configuration

#### Which issue(s) this PR fixes

fix [#285](https://github.com/open-component-model/ocm-project/issues/285)

fyi @morri-son

### CODE REVIEW

**Comment by morri-son** [comment]
@jakobmoellerdev just fixes half of [#285 ](https://github.com/open-component-model/ocm-project/issues/285). Is this enough for us and we don't need a rotten state?

**Comment by jakobmoellerdev** [comment]
Discussed Async:
1. We want 90 days stale interval
2. we start with only stale and add rotten later if we need it

**Review by morri-son — APPROVED** [review]
lgtm

**Comment by hilmarf** [comment]
@jakobmoellerdev / @morri-son - should we move this action to our central place:
https://github.com/open-component-model/.github/tree/main/.github/workflows and then call(reuse) it from every repo, where we want to clean/mark issues automatically?

see sample usage: https://github.com/open-component-model/ocm-website/blob/main/.github/workflows/verify.yml#L11

**Comment by jakobmoellerdev** [comment]
yes, great idea. I'll prepare a PR

**Pull request merged**
