### PR TITLE
fix: wrap the TLS config into a retryer client

### PR DESCRIPTION
**Pull request by Skarlso**
#### What this PR does / why we need it

Closes https://github.com/open-component-model/ocm-project/issues/273

### CODE REVIEW

**Review by hilmarf — DISMISSED** [review]

**Review by hilmarf — DISMISSED** [review]

**Comment by Skarlso** [comment]
```
go run main.go
Create context
Add credentials
Create component version at  /var/folders/gh/m47qw8n917n9gym8n_7ttlsc0000gn/T/509279416/ca
Transfer ctf to source registry
 2024-10-17T16:08:46+02:00 info    [ocm/transfer] "transferring version" history= version=test.org/test:1.0.0
 2024-10-17T16:08:46+02:00 info    [ocm/transfer] "  transferring references" history= version=test.org/test:1.0.0
Tranfer component version from source to destination registry
 2024-10-17T16:08:47+02:00 info    [ocm/transfer] "transferring version" history= version=test.org/test:1.0.0
 2024-10-17T16:08:47+02:00 info    [ocm/transfer] "  transferring references" history= version=test.org/test:1.0.0
 2024-10-17T16:08:47+02:00 info    [ocm/transfer] "  transferring resources" history= version=test.org/test:1.0.0
 2024-10-17T16:08:58+02:00 info    [ocm/transfer] "  transferring sources" history= version=test.org/test:1.0.0
 2024-10-17T16:08:58+02:00 info    [ocm/transfer] "  adding component version" history= version=test.org/test:1.0.0

```

Works with localhost https and custom certs. Also had to fix an issue with figuring out what blob to push and where.

**Comment by Skarlso** [comment]
```
ocm add componentversions --create  components.yaml -f
processing components.yaml...
  processing document 1...
    processing index 1
    processing index 2
    processing index 3
    processing index 4
found 4 components
adding component ocm.software/podinfo:1.0.5...
  adding source git: "name"="github_com_open_component_model_podinfo","version"="1.0.0"...
  adding reference ocm.software/podinfo/backend: "name"="backend","version"="1.0.0"...
  adding reference ocm.software/podinfo/frontend: "name"="frontend","version"="1.0.0"...
  adding reference ocm.software/redis: "name"="redis","version"="1.0.0"...
adding component ocm.software/podinfo/backend:1.0.0...
  adding source git: "name"="github_com_open_component_model_podinfo","version"="1.0.0"...
  adding resource configdata.ocm.software: "name"="config","version"="<componentversion>"...
  adding resource ociImage: "name"="image","version"="6.2.0"...
  adding resource kustomize.ocm.fluxcd.io: "name"="manifests","version"="<componentversion>"...
adding component ocm.software/podinfo/frontend:1.0.0...
  adding source git: "name"="github_com_open_component_model_podinfo","version"="1.0.0"...
  adding resource configdata.ocm.software: "name"="config","version"="<componentversion>"...
  adding resource ociImage: "name"="image","version"="6.2.0"...
  adding resource kustomize.ocm.fluxcd.io: "name"="manifests","version"="<componentversion>"...
adding component ocm.software/redis:1.0.0...
  adding source git: "name"="github_com_open_component_model_podinfo","version"="1.0.0"...
  adding resource configdata.ocm.software: "name"="config","version"="<componentversion>"...
  adding resource ociImage: "name"="image","version"="6.0.1"...
  adding resource kustomize.ocm.fluxcd.io: "name"="manifests","version"="<componentversion>"...
➜  podinfo git:(main) ✗ ocm add componentversions --create  components.yaml -f
➜  podinfo git:(main) ✗
➜  podinfo git:(main) ✗ ocm transfer commontransportarchive --copy-resources ./transport-archive ghcr.io/skarlso/ocm-transfer-test-20
transferring component "ocm.software/podinfo/frontend"...
  transferring version "ocm.software/podinfo/frontend:1.0.0"...
  ...resource 0 config[configdata.ocm.software]...
  ...resource 1 image[ociImage](stefanprodan/podinfo:6.2.0)...
  ...resource 2 manifests[kustomize.ocm.fluxcd.io]...
  ...adding component version...
transferring component "ocm.software/redis"...
  transferring version "ocm.software/redis:1.0.0"...
  ...resource 0 config[configdata.ocm.software]...
  ...resource 1 image[ociImage](library/redis:6.0.1)...
  ...resource 2 manifests[kustomize.ocm.fluxcd.io]...
  ...adding component version...
transferring component "ocm.software/podinfo"...
  transferring version "ocm.software/podinfo:1.0.5"...
  ...adding component version...
transferring component "ocm.software/podinfo/backend"...
  transferring version "ocm.software/podinfo/backend:1.0.0"...
  ...resource 0 config[configdata.ocm.software]...
  ...resource 1 image[ociImage](stefanprodan/podinfo:6.2.0)...
  ...resource 2 manifests[kustomize.ocm.fluxcd.io]...
  ...adding component version...
➜  podinfo git:(main) ✗
```

**Review by hilmarf — DISMISSED** [review]

**Review by jakobmoellerdev — APPROVED** [review]
Sorry took me some time to reproduce...
Thanks for the detailed code comment.
LGTM

**Review by hilmarf — APPROVED** [review]

**Comment by Skarlso** [comment]
Updating the branch in a sec.. I made it even nicer by asserting that specific error.

**Comment by Skarlso** [comment]
```go
	if err := n.ociRepo.PushReference(context.Background(), expectedDescriptor, reader, tag); err != nil {
		// If the manifest is unknown to the registry, which can occur with Docker,
		// we might be able to push the entire blob instead of a reference.
		// We can't assert the error because docker returns Manifest Unknown,
		// while ghcr.io or quay work with PushReference out of the box.
		// Meanwhile, we need to get the reader again, because PushReference exhausted it.
		manifestError := errcode.Error{}
		if errors.As(err, &manifestError) {
			if manifestError.Code == errcode.ErrorCodeManifestUnknown {
				reader, err = blob.Reader()
				if err != nil {
					return err
				}

				return n.ociRepo.Blobs().Push(context.Background(), expectedDescriptor, reader)
			}
		}

		return fmt.Errorf("failed to push reference %s: %w", tag, err)
	}
```

**Pull request merged**
