### PR TITLE
add back deleted deepcopy files

### PR DESCRIPTION
**Pull request by Skarlso**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release Notes**:

```feature user

```

### CODE REVIEW

**Review by phoban01 — DISMISSED** [review]

**Review by phoban01 — DISMISSED** [review]
LGTM

**Comment by Skarlso** [comment]
Can't push the fix. I will once Github works.

**Comment by Skarlso** [comment]
Can't push the fix. I will once Github works.

**Comment by Skarlso** [comment]
Can't push the fix. I will once Github works.

**Comment by Skarlso** [comment]
Can't push the fix. I will once Github works.

**Comment by Skarlso** [comment]
Can't push the fix. I will once Github works.

**Comment by Skarlso** [comment]
Going to add a target to install `controller-gen` and add a Github action to make sure generation is not broken.

**Review by phoban01 — APPROVED** [review]

**Review by jensh007 — APPROVED** [review]

**Pull request merged**
