### PR TITLE
feat: add silent flag and fix dry run with prerequisites

### PR DESCRIPTION
**Pull request by Skarlso**
## Description

Closes https://github.com/open-component-model/ocm-project/issues/37

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🎇 Restructuring
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

- Related Issue # (issue)
- Closes # (issue)
- Fixes # (issue)
> Remove if not applicable

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] Separate ticket for tests # (issue/pr)

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🙅 no documentation needed

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Skarlso** [comment]
```
./bin/ocm controller uninstall -p
► uninstalling ocm-controller with version latest
► got latest version "v0.21.1"
✔ successfully fetched install file
► applying to cluster...
► waiting for ocm deployment to be deleted
✔ ocm-controller successfully uninstalled
► uninstalling cert-manager and issuers
► uninstalling cert-manager with version v1.13.2
► remove certificate for internal registry
Error: ✗ failed to uninstall pre-requesits: ✗ failed to create registry certificate: failed to delete manifests: delete failed, errors: ClusterIssuer/ocm-issuer query failed: no matches for kind "ClusterIssuer" in version "cert-manager.io/v1";Certificate/ocm-system/ocm-registry-certificate query failed: no matches for kind "Certificate" in version "cert-manager.io/v1";

➜  ocm git:(add-moar-flags) ./bin/ocm controller uninstall --silent -p
► uninstalling ocm-controller with version latest
► got latest version "v0.21.1"
✔ successfully fetched install file
► applying to cluster...
► waiting for ocm deployment to be deleted
✔ ocm-controller successfully uninstalled
► uninstalling cert-manager and issuers
► uninstalling cert-manager with version v1.13.2
► remove certificate for internal registry

```

**Comment by hilmarf** [comment]
@robertwol - what did you have in mind for the `--silent` flag? What should happen?
https://github.com/open-component-model/ocm-project/issues/37

**Comment by Skarlso** [comment]
Robert said this:

Screenshot 2024-05-07 at 16 59 02

In my opinion silent usually suppresses logs but Robert specifically said `exit status` so... :) That's what I did. :D

**Comment by Skarlso** [comment]
Oh, and `-o yaml` is already done by dry run which just outputs the manifests it would have applied.

**Review by hilmarf — APPROVED** [review]

**Pull request merged**
