### PR TITLE
generalize resource selectors

### PR DESCRIPTION
**Pull request by mandelsoft**
**What this PR does / why we need it**:

Offer a public resource selector feature on the internal component descriptor version.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release Notes**:

```feature user

```

### CODE REVIEW

**Review by phoban01 — DISMISSED** [review]

**Review by Skarlso — DISMISSED** [review]
Nice! Thanks, Uwe!

**Comment by mandelsoft** [comment]
I've added resource selection via Labels and additionally tests for the new features.

**Comment by Skarlso** [comment]
Please try and not extend this any further. :D Also, we kind of need this for our tests sooner rather than later. :)

thanks! :)

**Comment by mandelsoft** [comment]
yes, it is done now. What I wanted to achieve are the same selection features for resources and references (and potentially sources).
Therefore, the selector interface had to be extended a little bit. But now it is in a shape to be extendable in a compatible manner. if some extension will be required in the future.

**Review by jensh007 — APPROVED** [review]

**Pull request merged**
