### PR TITLE
Revert "feat: replace docker with oras (#904)"

### PR DESCRIPTION
**Pull request by Skarlso**
This reverts commit 3cfa228726daebb061989b27b620698d24c555d2.

### CODE REVIEW

**Comment by jakobmoellerdev** [comment]
I think you would need to add no lints to make sure you dont break any future PRs
Other than that, Im fine

**Comment by Skarlso** [comment]
The linter is failing anyways... :D So I'll revert the docker things, but keep the linter modifications and the makefile changes. 👍

**Comment by frewilhelm** [comment]
https://github.com/open-component-model/ocm/pull/975 should be reverted as well, right?

**Comment by Skarlso** [comment]
> #975 should be reverted as well, right?

Yes, thanks.

**Review by jakobmoellerdev — APPROVED** [review]

**Review by fabianburth — APPROVED** [review]

**Pull request merged**
